PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT ?company (COUNT(?person) as ?speaker_count) (GROUP_CONCAT(?name; separator=", ") as ?speakers)
WHERE {
  ?person a foaf:Person ;
          foaf:name ?name .
  
  {
    ?person org:holds ?membership .
    ?membership org:organization ?org .
    ?org foaf:name ?company .
  }
  UNION
  {
    ?person org:memberOf ?org .
    ?org foaf:name ?company .
  }
}
GROUP BY ?company
ORDER BY DESC(?speaker_count) ?company